# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# Hyperparameters for VOC finetuning
# python train.py --batch 64 --weights yolov5m.pt --data VOC.yaml --img 512 --epochs 50
# See tutorials for hyperparameter evolution https://github.com/ultralytics/yolov5#tutorials

# Hyperparameter Evolution Results
# Generations: 306
#                   P         R     mAP.5 mAP.5:.95       box       obj       cls
# Metrics:        0.6     0.936     0.896     0.684    0.0115   0.00805   0.00146

defaults:
  - default_train_params

max_epochs: 300
lr_mode: cosine
cosine_final_lr_ratio: 0.12
lr_warmup_epochs: 2
warmup_momentum: 0.5
warmup_bias_lr: 0.05
initial_lr: 0.0032  # will be scaled according to num DDP processes

loss: yolo_v5_loss
criterion_params: ???
loss_logging_items_names: [GIoU, obj, cls, Loss]

optimizer: SGD
optimizer_params:
  momentum: 0.843
  weight_decay: 0.00036  # will be scaled according to effective batch size
  nesterov: True

ema: True
mixed_precision: False

valid_metrics_list:
  - _target_: super_gradients.training.metrics.DetectionMetrics
    post_prediction_callback:
      _target_: super_gradients.training.models.detection_models.yolov5.YoloV5PostPredictionCallback
    num_cls: 20

metric_to_watch: 'mAP@0.50:0.95'
greater_metric_to_watch_is_better: True

_convert_: all


