batch_size: 64 # batch size for trainset in CoCoDetectionDatasetInterface
val_batch_size: 64 # batch size for valset in CoCoDetectionDatasetInterface
val_image_size: 320 # image size for valset in CoCoDetectionDatasetInterface
train_image_size: 320 # image size for trainset in CoCoDetectionDatasetInterface

val_collate_fn: # collate function for valset in CoCoDetectionDatasetInterface
  _target_: super_gradients.training.utils.utils.load_func
  dotpath: super_gradients.training.utils.detection_utils.base_detection_collate_fn

train_collate_fn: # collate function for trainset in CoCoDetectionDatasetInterface
  _target_: super_gradients.training.utils.utils.load_func
  dotpath: super_gradients.training.utils.detection_utils.base_detection_collate_fn

val_sample_loading_method: "default"
dataset_hyper_param:
  hsv_h: 0.0138
  hsv_s: 0.664
  hsv_v: 0.464
  degrees: 0.373
  translate: 0.245
  scale: 0.898
  shear: 0.602

_convert_: all

box: 0.0296
cls: 0.243
cls_pw: 0.631
obj: 0.301
obj_pw: 0.911
iou_t: 0.2
fl_gamma: 0.0

perspective: 0.0
flipud: 0.00856
fliplr: 0.5
mosaic: 1.0
mixup: 0.243
copy_paste: 0.0